apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  {{- with .Values.excludedNamespaces }}
  EXCLUDE_NAMESPACES: '{{ join "," . }}'
  {{- end }}
  {{- if .Values.configMap.extraConfig }}
  {{- tpl .Values.configMap.extraConfig . | nindent 2 }}
  {{- end }}
