apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  EXCLUDE_NAMESPACES: '{{- join "," .Values.excludedNamespaces }}'
  {{- if .Values.configMap.extraConfig }}
  {{- tpl .Values.configMap.extraConfig . | nindent 2 }}
  {{- end }}
