{{- /* Only deploy when the user explicitly enables deployment AND the resource is included in includedResources */ -}}
{{- if and .Values.deployExtraResources.deployIngressClass (include "go-kube-downscaler.deployIngressClass" .) -}}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: kube-downscaler-ingress-class
spec:
  controller: kube-downscaler.k8s/gateway-controller
{{- end }}
