{{- if .Values.admissionController.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook.kube-downscaler.k8s
webhooks:
  - name: webhook.kube-downscaler.k8s
    rules:
{{- include "go-kube-downscaler.webhookresources" . | trim | nindent 6 }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - {{ .Release.Namespace }}
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "go-kube-downscaler.fullname" . }}-webhook
        path: /validate-workloads
        port: 443
      caBundle: {{ .Values.admissionController.certs.caBundle }}
    matchConditions:
      - name: 'exclude-downscaler-origin'
        expression: 'request.userInfo.username != "system:serviceaccount:{{ .Release.Namespace }}:{{ include "go-kube-downscaler.serviceAccountName" . }}"'
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Ignore
    timeoutSeconds: 8
{{- end }}
