{{- if or .Values.podDisruptionBudget.minAvailable .Values.podDisruptionBudget.maxUnavailable }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "go-kube-downscaler.webhookController.fullname" . }}
  labels:
    {{- include "go-kube-downscaler.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "go-kube-downscaler.selectorLabels" . | nindent 6 }}
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{-  if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
