{{- if .Values.admissionController.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: org.kube-downscaler.webhook
webhooks:
  - name: org.kube-downscaler.webhook
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - {{ .Release.Namespace }}
    rules:
{{ include "go-kube-downscaler.webhookresources" . | trim | nindent 6 }}
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "go-kube-downscaler.fullname" . }}-webhook
        path: /validate-workloads
        port: 443
      caBundle: {{ .Values.admissionController.caBundle }}
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Ignore
    timeoutSeconds: 8
{{- end }}
