{{- if and .Values.webhookController.enabled (not .Values.webhookController.certManager.enabled) }}
apiVersion: v1
data:
  tls.crt: {{ .Values.webhookController.certs.tlsCrt }}
  tls.key: {{ .Values.webhookController.certs.tlsKey }}
kind: Secret
metadata:
  name: {{ include "go-kube-downscaler.webhookController.fullname" . }}
  labels:
    {{- include "go-kube-downscaler.labels" . | nindent 4 }}
type: kubernetes.io/tls
{{- end }}
