{{- if .Values.webhookController.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-kube-downscaler.webhookController.fullname" . }}
  labels:
    {{- include "go-kube-downscaler.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "go-kube-downscaler.selectorLabels" . | nindent 6 }}-webhook
  type: ClusterIP
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
{{- end }}
