---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: admission-webhook
  name: admission-webhook-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: admission-webhook
