import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  DocsSidebar: [
    {
      type: "category",
      label: "Helm Chart",
      link: {
        type: "generated-index",
        title: "Helm Chart",
        description: "Documentation about contents of the Helm chart.",
        slug: "/docs/helm-chart",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "docs/helm-chart",
        },
      ],
    },
  ],
  GuidesSidebar: [
    {
      type: "category",
      label: "Getting Started",
      link: {
        type: "doc",
        id: "guides/getting-started",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "guides/getting-started",
        },
      ],
    },
  ],
};

export default sidebars;
