import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  DocsSidebar: [
    {
      type: "autogenerated",
      dirName: "docs",
    },
  ],
  GuidesSidebar: [
    {
      type: "autogenerated",
      dirName: "guides",
    },
  ],
};

export default sidebars;
