name: Create dev build

on:
  workflow_dispatch:

jobs:
  create_dev_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version: ${{ steps.chart_version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Chart Version
        id: chart_version
        run: |
          version=$(yq e '.version' ./deployments/chart/Chart.yaml)
          echo "version=$version" >> $GITHUB_OUTPUT

  docker_build:
    needs: create_dev_build
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker_build.yaml
    with:
      appVersion: "dev"
      setLatest: false
    secrets: inherit

  helm_build:
    needs: create_dev_build
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/helm_build.yaml
    with:
      version: "${{ needs.create_dev_build.outputs.version }}-dev"
      appVersion: "dev"
    secrets: inherit
